--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Dec 02 2021 15:06
-- Script Generated by Database Design Studio 2.21.3 
--


--
-- Select Database: 'db_name'
--
USE db_name
GO
 
IF DB_NAME() = 'db_name'
    RAISERROR('''db_name'' DATABASE CONTEXT NOW IN USE.',1,1)
ELSE
    RAISERROR('ERROR IN BATCH FILE, ''USE db_name'' FAILED!  KILLING THE SPID NOW.',22,127) WITH LOG
 
GO
EXECUTE SP_DBOPTION 'db_name' ,'TRUNC. LOG ON CHKPT.' ,'TRUE'
GO

--
-- Create Table    : 'Virksomhed'   
-- VirksomhedID    :  
-- CVR             :  
-- Virksomhedsnavn :  
-- KontaktPerson   :  
-- Email           :  
-- Password        :  
--
CREATE TABLE Virksomhed (
    VirksomhedID   INT NOT NULL UNIQUE,
    CVR            INT NOT NULL,
    Virksomhedsnavn NVARCHAR(30) NOT NULL,
    KontaktPerson  NVARCHAR(30) NOT NULL,
    Email          NVARCHAR(30) NOT NULL,
    Password       NVARCHAR(30) NOT NULL,
CONSTRAINT pk_Virksomhed PRIMARY KEY CLUSTERED (VirksomhedID))
GO

--
-- Create Table    : 'Bruger'   
-- BrugerID        :  
-- Fornavn         :  
-- Efternavn       :  
-- Foedselsdag     :  
-- Email           :  
-- Password        :  
--
CREATE TABLE Bruger (
    BrugerID       INT NOT NULL UNIQUE,
    Fornavn        NVARCHAR(20) NOT NULL,
    Efternavn      NVARCHAR(20) NOT NULL,
    Foedselsdag    CHAR(10) NOT NULL,
    Email          NVARCHAR(30) NOT NULL,
    Password       NVARCHAR(30) NOT NULL,
CONSTRAINT pk_Bruger PRIMARY KEY CLUSTERED (BrugerID))
GO

--
-- Create Table    : 'Pubcrawl'   
-- PubcrawlD       :  
-- PakkeNavn       :  
-- MoedeTid        :  
-- MoedeSted       :  
--
CREATE TABLE Pubcrawl (
    PubcrawlD      NCHAR(50) NOT NULL,
    PakkeNavn      NCHAR(50) NOT NULL,
    MoedeTid       NCHAR(50) NOT NULL,
    MoedeSted      NCHAR(50) NOT NULL,
CONSTRAINT pk_Pubcrawl PRIMARY KEY CLUSTERED (PubcrawlD))
GO

--
-- Create Table    : 'Har'   
-- PubcrawlD       :  (references Pubcrawl.PubcrawlD)
-- VirksomhedID    :  (references Virksomhed.VirksomhedID)
--
CREATE TABLE Har (
    PubcrawlD      NCHAR(50) NOT NULL,
    VirksomhedID   INT NOT NULL,
CONSTRAINT pk_Har PRIMARY KEY CLUSTERED (PubcrawlD,VirksomhedID),
CONSTRAINT fk_Har FOREIGN KEY (PubcrawlD)
    REFERENCES Pubcrawl (PubcrawlD)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
CONSTRAINT fk_Har2 FOREIGN KEY (VirksomhedID)
    REFERENCES Virksomhed (VirksomhedID)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'Harr'   
-- PubcrawlD       :  (references Pubcrawl.PubcrawlD)
-- BrugerID        :  (references Bruger.BrugerID)
--
CREATE TABLE Harr (
    PubcrawlD      NCHAR(50) NOT NULL,
    BrugerID       INT NOT NULL,
CONSTRAINT pk_Harr PRIMARY KEY CLUSTERED (PubcrawlD,BrugerID),
CONSTRAINT fk_Harr FOREIGN KEY (PubcrawlD)
    REFERENCES Pubcrawl (PubcrawlD)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
CONSTRAINT fk_Harr2 FOREIGN KEY (BrugerID)
    REFERENCES Bruger (BrugerID)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Permissions for: 'public'
--
GRANT ALL ON Virksomhed TO public
GO
GRANT ALL ON Bruger TO public
GO
GRANT ALL ON Pubcrawl TO public
GO
GRANT ALL ON Har TO public
GO
GRANT ALL ON Harr TO public
GO

