--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Nov 04 2021 11:57
-- Script Generated by Database Design Studio 2.21.3 
--


--
-- Select Database: 'db_name'
--
USE db_name
GO
 
IF DB_NAME() = 'db_name'
    RAISERROR('''db_name'' DATABASE CONTEXT NOW IN USE.',1,1)
ELSE
    RAISERROR('ERROR IN BATCH FILE, ''USE db_name'' FAILED!  KILLING THE SPID NOW.',22,127) WITH LOG
 
GO
EXECUTE SP_DBOPTION 'db_name' ,'TRUNC. LOG ON CHKPT.' ,'TRUE'
GO

--
-- Create Table    : 'CityCrawl'   
-- CC__id          :  
--
CREATE TABLE CityCrawl (
    CC__id         INT IDENTITY(1,1) NOT NULL UNIQUE,
CONSTRAINT pk_CityCrawl PRIMARY KEY CLUSTERED (CC__id))
GO

--
-- Create Table    : 'Virksomhed'   
-- Virksomhed_id   :  
-- CVR             :  
-- Virksomhedsnavn :  
-- KontaktPerson   :  
-- Email           :  
-- Password        :  
-- CC__id          :  (references CityCrawl.CC__id)
--
CREATE TABLE Virksomhed (
    Virksomhed_id  INT NOT NULL UNIQUE,
    CVR            NVARCHAR(8) NOT NULL,
    Virksomhedsnavn NVARCHAR(30) NOT NULL,
    KontaktPerson  NVARCHAR(30) NOT NULL,
    Email          NVARCHAR(30) NOT NULL,
    Password       NVARCHAR(30) NOT NULL,
    CC__id         INT NULL,
CONSTRAINT pk_Virksomhed PRIMARY KEY CLUSTERED (Virksomhed_id),
CONSTRAINT fk_Virksomhed FOREIGN KEY (CC__id)
    REFERENCES CityCrawl (CC__id)
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'Bruger'   
-- Bruger_id       :  
-- Navn            :  
-- Efternavn       :  
-- Foedselsdag     :  
-- Email           :  
-- Password        :  
-- CC__id          :  (references CityCrawl.CC__id)
--
CREATE TABLE Bruger (
    Bruger_id      INT NOT NULL UNIQUE,
    Navn           NVARCHAR(20) NOT NULL,
    Efternavn      NVARCHAR(20) NOT NULL,
    Foedselsdag    CHAR(10) NOT NULL,
    Email          NVARCHAR(30) NOT NULL,
    Password       NVARCHAR(30) NOT NULL,
    CC__id         INT NULL,
CONSTRAINT pk_Bruger PRIMARY KEY CLUSTERED (Bruger_id),
CONSTRAINT fk_Bruger FOREIGN KEY (CC__id)
    REFERENCES CityCrawl (CC__id)
    ON UPDATE CASCADE)
GO

--
-- Permissions for: 'public'
--
GRANT ALL ON CityCrawl TO public
GO
GRANT ALL ON Virksomhed TO public
GO
GRANT ALL ON Bruger TO public
GO

