--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Oct 28 2021 14:43
-- Script Generated by Database Design Studio 2.21.3 
--


--
-- Select Database: 'db_name'
--
USE db_name
GO
 
IF DB_NAME() = 'db_name'
    RAISERROR('''db_name'' DATABASE CONTEXT NOW IN USE.',1,1)
ELSE
    RAISERROR('ERROR IN BATCH FILE, ''USE db_name'' FAILED!  KILLING THE SPID NOW.',22,127) WITH LOG
 
GO
EXECUTE SP_DBOPTION 'db_name' ,'TRUNC. LOG ON CHKPT.' ,'TRUE'
GO

--
-- Create Table    : 'Virksomhed'   
-- Virksomhed_id   :  
-- CVR             :  
-- Virksomhedsnavn :  
-- KontaktPerson   :  
-- Email           :  
-- Password        :  
--
CREATE TABLE Virksomhed (
    Virksomhed_id  INT NOT NULL UNIQUE,
    CVR            NVARCHAR(8) NOT NULL,
    Virksomhedsnavn NVARCHAR(30) NOT NULL,
    KontaktPerson  NVARCHAR(30) NOT NULL,
    Email          NVARCHAR(30) NOT NULL,
    Password       NVARCHAR(30) NOT NULL,
CONSTRAINT pk_Virksomhed PRIMARY KEY CLUSTERED (Virksomhed_id))
GO

--
-- Create Table    : 'Bruger'   
-- Bruger_id       :  
-- Navn            :  
-- Efternavn       :  
-- Foedselsdag     :  
-- Email           :  
-- Password        :  
--
CREATE TABLE Bruger (
    Bruger_id      INT NOT NULL UNIQUE,
    Navn           NVARCHAR(20) NOT NULL,
    Efternavn      NVARCHAR(20) NOT NULL,
    Foedselsdag    CHAR(10) NOT NULL,
    Email          NVARCHAR(30) NOT NULL,
    Password       NVARCHAR(30) NOT NULL,
CONSTRAINT pk_Bruger PRIMARY KEY CLUSTERED (Bruger_id))
GO

--
-- Permissions for: 'public'
--
GRANT ALL ON Virksomhed TO public
GO
GRANT ALL ON Bruger TO public
GO

